name: API Automation Workflow

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write      # needed to push to gh-pages

env:
  BLOCK_SEVERITIES: blocker,critical,sev1,p0

jobs:
  api-automation-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Run API Tests
        run: mvn -B clean test -DsuiteXmlFile=testng.xml -Dallure.results.directory=target/allure-results

      # Verify allure results exist
      - name: Verify Allure results exist (excluding history)
        id: verify
        run: |
          RESULT_COUNT=$(find target/allure-results -type f -name "*.json" -not -path "*/history/*" 2>/dev/null | wc -l | tr -d ' ')
          echo "count=$RESULT_COUNT" >> $GITHUB_OUTPUT
          if [ "$RESULT_COUNT" -eq 0 ]; then
            echo "::error::No Allure test results were produced."
            exit 1
          fi

      # --- Pull previous history from gh-pages branch ---
      - name: Checkout gh-pages branch (if exists)
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
        continue-on-error: true

      - name: Bring over previous Allure history
        run: |
          mkdir -p target/allure-results/history
          if [ -d "gh-pages/history" ]; then
            echo "Found previous history in gh-pages. Copying..."
            cp -r gh-pages/history/* target/allure-results/history/ || true
          else
            echo "No previous history available."
          fi
      # ---------------------------------------------------

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev

      - name: Generate Allure Report
        run: allure generate target/allure-results -o target/allure-report --clean

      - name: Upload Allure Report (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

      # ---------- Publish report to GitHub Pages ----------
      - name: Publish Allure report to gh-pages
        if: steps.verify.outputs.count != '0'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: target/allure-report
          keep_files: true              # keeps previous history directory
          force_orphan: false           # maintain history
      # -----------------------------------------------------

      - name: Gate PR on severe failures
        if: always()
        run: |
          sudo apt-get update -y >/dev/null 2>&1 && sudo apt-get install -y jq >/dev/null 2>&1 || true
          jq -r --arg block "${BLOCK_SEVERITIES}" '
            ( $block | ascii_downcase | split(",") ) as $sevlist
            |
            select(.status=="failed" or .status=="broken")
            |
            (.labels // [] | map(select(.name=="severity") | .value | ascii_downcase) | .[0] // "unknown") as $sev
            |
            select( ($sevlist | index($sev)) != null )
            |
            [ $sev, .status, (.name // .fullName // "unknown") ] | @tsv
          ' target/allure-results/*.json 2>/dev/null | tee .blocked.tsv

          BLOCK_COUNT=$(wc -l < .blocked.tsv | tr -d ' ')
          {
            echo "### Severe test failures (blocking)"
            echo ""
            echo "| Severity | Status | Test |"
            echo "|---|---|---|"
            if [ "$BLOCK_COUNT" -gt 0 ]; then
              awk -F'\t' '{printf("| %s | %s | %s |\n",$1,$2,$3)}' .blocked.tsv
            else
              echo "| — | — | — |"
            fi
          } >> "$GITHUB_STEP_SUMMARY"

          if [ "${{ github.event_name }}" = "pull_request" ] && [ "$BLOCK_COUNT" -gt 0 ]; then
            echo "::error::Severe test failures detected ($BLOCK_COUNT). Blocking this PR."
            exit 1
          fi
